### ISSUE TITLE
400 Bad Request: malformed Host header (Docker::Error::ClientError)

### ISSUE THREAD

**Issue by patricktruebe** [scoutapp/docker-scout#5] opened 2016-12-14 21:33 UTC
Setup like Documentation fails with

```sh
root@cattle2:/etc/scout# docker logs scout-agent 
scoutd: 2016/12/14 21:26:36 Logging to /var/log/scout/scoutd.log
/var/lib/gems/1.9.1/gems/docker-api-1.22.4/lib/docker/connection.rb:42:in `rescue in request': 400 Bad Request: malformed Host header (Docker::Error::ClientError)
	from /var/lib/gems/1.9.1/gems/docker-api-1.22.4/lib/docker/connection.rb:38:in `request'
	from /var/lib/gems/1.9.1/gems/docker-api-1.22.4/lib/docker/connection.rb:65:in `block (2 levels) in <class:Connection>'
	from /var/lib/gems/1.9.1/gems/docker-api-1.22.4/lib/docker/event.rb:20:in `stream'
	from /docker_events.rb:11:in `<main>'
```

```sh
root@cattle2:/etc/scout# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                       NAMES
611a5693c220        scoutapp/docker-scout:latest   "sh start.sh"            8 seconds ago       Up 8 seconds                                    scout-agent
```

```sh
root@cattle2:/tmp/bugrepo# uname -a
Linux cattle2.relenda.io 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@cattle2:/tmp/bugrepo# free -m
              total        used        free      shared  buff/cache   available
Mem:          48302        4376       40589         902        3336       42066
Swap:          3899           0        3899
root@cattle2:/tmp/bugrepo# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
root@cattle2:/tmp/bugrepo# docker -D info
Containers: 20
 Running: 12
 Paused: 0
 Stopped: 8
Images: 74
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 213
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 47.17 GiB
Name: cattle2.relenda.io
ID: JFKD:RDCX:SD7H:WULI:T2ZC:7QGP:YV4V:5L4K:JUE4:UZVD:C5KB:6RHH
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
root@cattle2:/tmp/bugrepo# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by andre** [comment] 2016-12-14 21:51
Hi Patrick, I just responded via email.

**Comment by andre** [comment] 2016-12-16 04:01
For future references: 

* If you are experiencing this issue with docker-scout itself, the issue is fixed with a new version of [docker-scout](https://hub.docker.com/r/scoutapp/docker-scout/)
* If you are experiencing this issue running scoutd directly on a host, it is typically fixed by upgrading your `excon` gem to a newer version

**Closed by andre** 2016-12-16 04:01 UTC

**Comment by patricktruebe** [comment] 2017-01-09 16:42
Thank you!
